'use strict';

/**
 * bcu_v1 contract constants (Stage 1 validate).
 * Gates calibrated on n=6 real captures — provisional, not statistically validated.
 */

const EXTRACTION_CONTRACT_VERSION = 'bcu_v1';

const CURRENCY_VIEWS = Object.freeze([
  'MN_PESOS_ME_PESOS',
  'MN_PESOS_ME_USD',
  'MN_USD_ME_USD',
  'UNKNOWN',
]);

/** V1: only this view may reach REVIEW_READY (no FX / no reinterpretation). */
const CURRENCY_VIEW_REVIEW_READY = 'MN_PESOS_ME_PESOS';

const RUBRO_KEYS = Object.freeze([
  'vigente',
  'vigente_no_autoliquidable',
  'moroso',
  'castigado_por_atraso',
  'contingencias',
  'creditos_reestructurados',
]);

const MONEY_SIDES = Object.freeze(['mn', 'me']);

const CLASSIFICATION = Object.freeze({
  REVIEW_READY: 'REVIEW_READY',
  HUMAN_REVIEW: 'HUMAN_REVIEW',
  EXTRACTION_FAILED: 'EXTRACTION_FAILED',
});

const REASON = Object.freeze({
  EXTRACTION_MISSING: 'EXTRACTION_MISSING',
  EXTRACTION_NOT_OBJECT: 'EXTRACTION_NOT_OBJECT',
  EXTRACTION_CONTRACT_INVALID: 'EXTRACTION_CONTRACT_INVALID',
  AMOUNT_NOT_FINITE: 'AMOUNT_NOT_FINITE',
  AMOUNT_NEGATIVE: 'AMOUNT_NEGATIVE',
  AMOUNT_PRECISION_INVALID: 'AMOUNT_PRECISION_INVALID',
  AMOUNT_UNSUPPORTED_TYPE: 'AMOUNT_UNSUPPORTED_TYPE',
  CI_MISSING: 'CI_MISSING',
  CI_MISMATCH: 'CI_MISMATCH',
  CURRENCY_VIEW_MISSING: 'CURRENCY_VIEW_MISSING',
  CURRENCY_VIEW_INVALID: 'CURRENCY_VIEW_INVALID',
  CURRENCY_VIEW_NOT_MN_PESOS_ME_PESOS: 'CURRENCY_VIEW_NOT_MN_PESOS_ME_PESOS',
  SUMMARY_DETAIL_MISMATCH: 'SUMMARY_DETAIL_MISMATCH',
  SUMMARY_DETAIL_NOT_COMPARABLE: 'SUMMARY_DETAIL_NOT_COMPARABLE',
  RUBRO_ORPHAN_INCONSISTENT_SUPPORT: 'RUBRO_ORPHAN_INCONSISTENT_SUPPORT',
  RUBRO_ORPHAN_SUMMARY_WITHOUT_INST: 'RUBRO_ORPHAN_SUMMARY_WITHOUT_INST',
  STRUCTURE_SUMMARY_WITHOUT_INSTITUTIONS: 'STRUCTURE_SUMMARY_WITHOUT_INSTITUTIONS',
  STRUCTURE_DUPLICATE_INSTITUTION: 'STRUCTURE_DUPLICATE_INSTITUTION',
  STRUCTURE_EMPTY_INSTITUTION_NAME: 'STRUCTURE_EMPTY_INSTITUTION_NAME',
  STRUCTURE_INSTITUTIONS_NOT_ARRAY: 'STRUCTURE_INSTITUTIONS_NOT_ARRAY',
  CATEGORY_INVALID: 'CATEGORY_INVALID',
});

module.exports = {
  EXTRACTION_CONTRACT_VERSION,
  CURRENCY_VIEWS,
  CURRENCY_VIEW_REVIEW_READY,
  RUBRO_KEYS,
  MONEY_SIDES,
  CLASSIFICATION,
  REASON,
};
