-- Autonomous SMS campaigns via Notifyme (T2voice).
-- Isolated from Credizona CRM and other MIE pipelines.
-- unique_id is a Postgres bigint identity (signed long for Notifyme).
-- Application code MUST keep unique_id as a decimal string — never Number/parseInt.

BEGIN;

CREATE TABLE IF NOT EXISTS public.sms_campaigns (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  name text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  total_messages integer NOT NULL DEFAULT 0,
  status text NOT NULL DEFAULT 'sending',
  CONSTRAINT sms_campaigns_status_check
    CHECK (status IN ('sending', 'sent', 'partial_error', 'error'))
);

CREATE TABLE IF NOT EXISTS public.sms_messages (
  unique_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  campaign_id uuid NOT NULL REFERENCES public.sms_campaigns(id) ON DELETE CASCADE,
  submission_order integer NOT NULL,
  phone text NOT NULL,
  text text NOT NULL,
  scheduled_at timestamptz NULL,
  status text NOT NULL DEFAULT 'pending',
  delivered_at timestamptz NULL,
  fail_reason text NULL,
  response_text text NULL,
  response_received_at timestamptz NULL,
  last_polled_at timestamptz NULL,
  source_system text NULL,
  source_record_id text NULL,
  czuid text NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT sms_messages_campaign_submission_order_unique
    UNIQUE (campaign_id, submission_order)
);

CREATE INDEX IF NOT EXISTS idx_sms_messages_campaign_id
  ON public.sms_messages (campaign_id);

CREATE INDEX IF NOT EXISTS idx_sms_messages_status
  ON public.sms_messages (status);

CREATE INDEX IF NOT EXISTS idx_sms_messages_campaign_id_status
  ON public.sms_messages (campaign_id, status);

CREATE INDEX IF NOT EXISTS idx_sms_messages_source_ref
  ON public.sms_messages (source_system, source_record_id)
  WHERE source_record_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_sms_messages_czuid
  ON public.sms_messages (czuid)
  WHERE czuid IS NOT NULL;

-- Copanel commercial pricing (not returned by Notifyme).
CREATE TABLE IF NOT EXISTS public.sms_cost_config (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  effective_from date NOT NULL,
  cost_per_sms_ex_vat numeric NOT NULL,
  vat_rate numeric NOT NULL DEFAULT 0.22,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_sms_cost_config_effective_from
  ON public.sms_cost_config (effective_from DESC);

COMMENT ON TABLE public.sms_campaigns IS
  'Notifyme SMS campaigns. Autonomous from Credizona CRM.';
COMMENT ON TABLE public.sms_messages IS
  'Per-message Notifyme rows. unique_id is the signed long sent as dataSms.uniqueId.';
COMMENT ON COLUMN public.sms_messages.unique_id IS
  'Postgres identity bigint. Keep as decimal string in app code; never coerce to JS Number.';
COMMENT ON COLUMN public.sms_messages.submission_order IS
  'Zero-based original order within the campaign; used to rebuild SOAP payload order.';
COMMENT ON COLUMN public.sms_messages.czuid IS
  'Optional external identity reference provided by the caller only. Never inferred from phone.';
COMMENT ON TABLE public.sms_cost_config IS
  'Copanel SMS cost schedule (ex-VAT + VAT rate). Not Notifyme data.';

COMMIT;
